version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Create NPMRC
          command: echo $NPMRC > ~/repo/.npmrc
      - run:
          name: update npm
          command: sudo npm i npm@6.8.0 -g
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Git user identification
          command: git config user.email "circleci@debitoor.com" && git config user.name "Circle Ci"
      - run:
          name: Checkout package.json
          command: git checkout package.json
      - run:
          name: Git push
          command: var=$(git status | grep package-lock.json | wc -l) && [ ! -z $var ] && git add package-lock.json && git commit -m "update pkg lock" && git push origin $CIRCLE_BRANCH || git status
      - run:
          name: NPM Test
          command: npm test
workflows:
   version: 2.1
   test:
     jobs:
       - test:
           context: NPM