version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Create NPMRC
          command: echo $NPMRC > ~/repo/.npmrc
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: NPM Test
          command: npm test
workflows:
   version: 2.1
   test:
     jobs:
       - test:
           context: NPM